### ISSUE TITLE
Can not use the IBM Cloud Function's Github Trigger with Enterprise Github

### ISSUE THREAD

**Issue by bogy0** [ibm-cloud-docs/openwhisk#179]
Hello!

Is it possible to use the IBM Cloud Function's Github Trigger in an Enterprise Github for example: https://github.ibm.com/ ?

I try to create some test triggers, but i can't find any enterprise related section in this doc:
https://cloud.ibm.com/docs/openwhisk?topic=cloud-functions-pkg_github

I created a Personal Access Token, but I get an error message when I try to create a new trigger. (bad credentials)

**Comment by kersten1** [comment]
Hello,
Unfortunately it is not possible to use the IBM Cloud Functions with Enterprise github repositories. I've added a note to the top of the article expressing this.
I apologize for any inconvenience.  Let me know if there is anything else I can help you with.

**Comment by bogy0** [comment]
No problem. Thanks for the answer. I closed this issue.
