### ISSUE TITLE
Weather Company Data for IBM Cloud service retirement

### ISSUE THREAD

**Issue by francesca-gigante** [ibm-cloud-docs/openwhisk#180]
The service has been retired and is no more available in the catalog at all https://www.ibm.com/cloud/blog/announcements/important-changes-related-to-weather-company-data-for-ibm-cloud

Even existing cf actions do not work any more
Please update the page.
Thanks

**Comment by kersten1** [comment]
Definitely looking into this. I knew that you could not provision a new weather service, but thought that the actions were still functional.

**Comment by davetropeano** [comment]
So I think the question is whether Cloud Functions needs to annotate the docs but keep the action available until Nov 20,2020 or whether we can delete right now.

**Comment by francesca-gigante** [comment]
I had a Weather service since long time but the cloud function was not working because the binding has disappeared and no way to create it again, even following the provided guide in the doc.

Then I deleted the weather services before realising that it was not possible to create it again.

**Comment by kersten1** [comment]
Removed
