### ISSUE TITLE
How call other actions from an action (not in the same sequence)?

### ISSUE THREAD

**Issue by filippotramonto** [ibm-cloud-docs/openwhisk#182]
In the docs page https://cloud.ibm.com/docs/openwhisk?topic=cloud-functions-about it is written:
> **Can I use more than one action at a time?**
> Yes! You can use actions to call other actions ....

But I have not found in the docs how to do this.
Could you point me to the docs where this is explained?
Or if it is not present, could you add the explanation?
Thanks

**Comment by kersten1** [comment]
Hi @ftram, your comment is definitely a worthy one and I appreciate you bringing it to my attention. We are looking at updating the content. Thank you!

**Comment by kersten1** [comment]
Hello @filippotramonto ,
We have created some new content that you might be interested in!  Try this out: https://cloud.ibm.com/docs/openwhisk?topic=openwhisk-tutorial_action
