### ISSUE TITLE
Incorrect package name for IBM Watson SDK

### ISSUE THREAD

**Issue by victorshinya** [ibm-cloud-docs/openwhisk#185]
Reading the documentation, I've found an incorrect package name for IBM Watson SDK on [Node.js packages](https://cloud.ibm.com/docs/openwhisk?topic=openwhisk-runtimes#node-js-packages). It's written `ibmwatson` but the correct name is `ibm-watson`.

**Where**: https://cloud.ibm.com/docs/openwhisk?topic=openwhisk-runtimes#openwhisk_ref_javascript_environments
**Text**: ibmwatson | Node.js client library to use the Watson APIs.

**Comment by kersten1** [comment]
That is depressing!  Thank you, @victorshinya, for pointing this out. Docs will be updated soon.

**Comment by victorshinya** [comment]
Sure! No problem! I opened a pull request with the fix.
