### ISSUE TITLE
Missing instruction for loggin to Docker

### ISSUE THREAD

**Issue by filippotramonto** [ibm-cloud-docs/openwhisk#187]
Hello,
I was following the instructions in https://cloud.ibm.com/docs/openwhisk?topic=openwhisk-prep#prep_python_docker in order to create a custom Docker image for an action written in Python.
But at the point (2) "Push your image to Docker Hub" the command did not work. So after some resarch on the web I realised thtat I have to loggin to Docker Hub via cli before pushing the image. 

I think it better insert in the docs this necessary instruction.

Similarly the instruction is missing also in the similar section to build a custom image for actions in ohter languages: https://cloud.ibm.com/docs/openwhisk?topic=openwhisk-prep#creating-a-custom-docker-image-for-your-action

**Comment by kersten1** [comment]
@filippotramonto You timed your comment well! I updated the docs with a tip in the sections that you suggested and the change should already be live: https://cloud.ibm.com/docs/openwhisk?topic=openwhisk-prep#prep_python_docker

Let me know if you spot anything else.
