### ISSUE TITLE
Error in Creating a trigger that listens to an Event Streams instance

### ISSUE THREAD

**Issue by ehoodkatzatwork** [ibm-cloud-docs/openwhisk#189]
The code for creating a trigger is incorrect. It results in getting an error message
"error: Unable to create trigger XXX Unable to configure feed XXX The supplied authentication is not authorized to access XXX"
https://cloud.ibm.com/docs/openwhisk?topic=openwhisk-pkg_event_streams#eventstreams_trigger

**Comment by kersten1** [comment]
Section was updated.
