### ISSUE TITLE
Wrong trigger create command

### ISSUE THREAD

**Issue by kpavel** [ibm-cloud-docs/openwhisk#190]
In this [section](https://cloud.ibm.com/docs/openwhisk?topic=openwhisk-pkg_event_streams#eventstreams_trigger) the trigger create command is wrong.
**-f /myOrg_mySpace/Service credentials-1/messageHubFeed** points to non existing resource instead of feed action.

I would recommend to ask user run:
```ibmcloud fn package list | grep MyEventStreamBind```

And use the output in create trigger command. The **myOrg_mySpace** confusing as well:
ibmcloud fn trigger create mytrigger -f <"output of the command above">/messageHubFeed -p topic mytopic

**Comment by kersten1** [comment]
Agreed! Moved to internal issue
