### ISSUE TITLE
I cannot access to Monitoring with Sysdig metrics for IBM Cloud Functions

### ISSUE THREAD

**Issue by filippotramonto** [ibm-cloud-docs/openwhisk#191]
I want enable the monitoring of the actions on IBM Cloud Functions and I have followed the docs https://cloud.ibm.com/docs/openwhisk?topic=openwhisk-monitor-sysdig but at the point 4 of "Accessing your Monitoring with Sysdig metrics" I don't see "IBM->Cloud Functions - Customer Metrics Dashboard." in Dashboards.
I have tried to search "IBM" and "functions" in the search bar in Dashboard but I have not found anything.

**Comment by kersten1** [comment]
Moved to internal repo .
