### ISSUE TITLE
Section of docs outdated on Cloudant binding

### ISSUE THREAD

**Issue by filippotramonto** [ibm-cloud-docs/openwhisk#192]
In the section [Binding the /whisk.system/cloudant package to your IBM Cloudant database.](https://cloud.ibm.com/docs/openwhisk?topic=openwhisk-pkg_cloudant&locale=en#binding-the-whisk-system-cloudant-package-to-your-ibm-cloudant-database-) of the [docs page on Cloudant binding](https://cloud.ibm.com/docs/openwhisk?topic=openwhisk-pkg_cloudant) at the point 6, the 'Example output' and sentence "the credentials for the IBM Cloudant service belong to a parameter named `__bx_creds`" are outdated since the `__bx_creds` parameter is no longer present in the parameters of the package /whisk.system/cloudant.

**Comment by kersten1** [comment]
Moved to internal issue.
