### ISSUE TITLE
Label is missing {{site.data.keyword.cloud_notm:}}

### ISSUE THREAD

**Issue by lionelmace** [ibm-cloud-docs/openwhisk#193]
Label is missing {{site.data.keyword.cloud_notm:}} on this page
https://cloud.ibm.com/docs/openwhisk?topic=openwhisk-monitor-sysdig

![image](https://user-images.githubusercontent.com/12241613/106296126-8d741480-6251-11eb-8d72-8cb30d9d566f.png)

**Comment by kersten1** [comment]
Thank you! Fixed...
