### ISSUE TITLE
Cloud Functions COS New Trigger Configuration "Learn More" link goes nowhwere

### ISSUE THREAD

**Issue by lakebandit** [ibm-cloud-docs/openwhisk#194]
Clicking on the Learn more link after the sentence "There are no Cloud Object Storage service instances enabled for this namespace.  "  when trying to connect a Cloud Object Storage trigger is broken link.
The link for the learn more is:  `https://cloud.ibm.com/docs/openwhisk?topic=cloud-functions-pkg_obstorage#pkg_obstorage_ev`

Please fix, broken links in the UI not good UX.

![Screen Shot 2021-06-25 at 20 58 41](https://user-images.githubusercontent.com/50970538/123498895-4b7cae00-d5f8-11eb-9ba3-9bfe1ec8a191.png)

![Screen Shot 2021-06-25 at 21 00 20](https://user-images.githubusercontent.com/50970538/123498908-6e0ec700-d5f8-11eb-8d29-6c2fc512ec2b.png)

**Comment by lakebandit** [comment]
This may be UI issue and not doc issue.  Can you route to the right repo if UI change needed.

**Comment by kersten1** [comment]
hello! Sorry about the bad link. Definitely not cool! I opened an issue with the UI team about the broken link and have also issued a redirect to point to the new URL.  Not sure who will get the link fixed first :)

In the meantime, the page you are looking for is here: https://cloud.ibm.com/docs/openwhisk?topic=openwhisk-pkg_obstorage#pkg_obstorage_ev

Thank you!

**Comment by kersten1** [comment]
Link is fixed but I do not know who one as both fixes went out at the same time. Thank you again for the input.
