### ISSUE TITLE
Broken link in docs.

### ISSUE THREAD

**Issue by jinwookjungs** [ibm-cloud-docs/openwhisk#196]
Hi, I found a broke link in this page: https://cloud.ibm.com/docs/openwhisk?topic=openwhisk-test#test-js.

The link "[ibmcloud fn action invoke](https://cloud.ibm.com/docs/openwhisk?topic=cloud-functions-cli-plugin-functions-cli#cli_action_invoke)" is broken.

Thanks.

**Comment by kersten1** [comment]
Hello! 

Sorry to be silent so long but it took a bit to get them all fixed. 
Thank you for pointing this error out to us.

Thank you
Kersten
